.TH new_lines 1 new_lines\-1.0
.SH NAME
new_lines \- Print specific number of new lines.
.SH SYNOPSIS
.B new_lines
.RB [ <n> | h ]
.SH DESCRIPTION
new_lines is a program to print a specific number of new lines to stdout.
.SH USAGE
.TP
.BI "<n>"
How many new lines to print
.TP
.BI " h"
Print usage
.SH EXIT STATUS
Always 0
.SH AUTHOR
.EX
Lucas Mior   <lucas.mior at tutamail.com>
.EE
